### ISSUE TITLE
incompatibility with numpy version 2+

### ISSUE THREAD

**Issue by wariobrega** [anthbapt/multixrank#11]
Hello,

First of all, congratulations on your package!

I want to point out a problem with multixrank installation from the default channel (`pip`).

I followed the instructions in the README, created a dedicated `conda` environment, and installed `multixrank` from pip.

However, when I try to import the library, I get the following error

```
>>> import multixrank
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/pasteur/appa/homes/dcapocef/miniconda3/envs/multixrank/lib/python3.10/site-packages/multixrank/__init__.py", line 18, in <module>
    from multixrank.BipartiteAll import BipartiteAll
  File "/pasteur/appa/homes/dcapocef/miniconda3/envs/multixrank/lib/python3.10/site-packages/multixrank/BipartiteAll.py", line 1, in <module>
    import networkx
  File "/pasteur/appa/homes/dcapocef/miniconda3/envs/multixrank/lib/python3.10/site-packages/networkx/__init__.py", line 64, in <module>
    import networkx.readwrite
  File "/pasteur/appa/homes/dcapocef/miniconda3/envs/multixrank/lib/python3.10/site-packages/networkx/readwrite/__init__.py", line 15, in <module>
    from networkx.readwrite.graphml import *
  File "/pasteur/appa/homes/dcapocef/miniconda3/envs/multixrank/lib/python3.10/site-packages/networkx/readwrite/graphml.py", line 344, in <module>
    class GraphML:
  File "/pasteur/appa/homes/dcapocef/miniconda3/envs/multixrank/lib/python3.10/site-packages/networkx/readwrite/graphml.py", line 377, in GraphML
    (np.float_, "float"),
  File "/pasteur/appa/homes/dcapocef/miniconda3/envs/multixrank/lib/python3.10/site-packages/numpy/__init__.py", line 400, in __getattr__
    raise AttributeError(
AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use `np.float64` instead.
```

I believe this is due to an incompatibility between the current `numpy` version and the one used by mutlixrank.

I solved this issue by downgrading `numpy` to version 1.26.4.

I Hope this helps in fixing the issue.

Best,

Daniele

**Comment by anthbapt** [comment]
Hello Daniele,

Thank you very much for the information, I had planned to update multiXrank for 3 months now, but I started a new position at King's College London, that prevent me to do it before. I will try to release an update for multiXrank with a compatibility with numpy 2.0 and networkx 3.3 tomorrow or on Friday.

Best wishes,
Anthony

**Comment by anthbapt** [comment]
Hello,

Multixrank version 0.3 just released (both in Github and Pypi), it should correct all issues.

Best wishes,
Anthony

PS: Let me know if everything is fine
